# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mustached coder
email: antol.peshkov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Antol Peshkov's blog about work and little bit about life. 
  Using Objective-C, Swift, Ruby and English with varying degrees of success.
  Worked at such apps as Buy Me a Pie, easyJet and Lifehacker
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://antol.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  antol

# Build settings
markdown: kramdown
